### PR TITLE
Move to be a >= 3.8 Python Project

### LINKED ISSUE #788: Move to >= 3.8 Project
Time has come, 3.6 is now 4 years old. 3.8 is almost 1.25 years old. I feel we can now move to and become a >=3.8 project.

We offer Docker images too now that can be used on older OS's.

This will open us up to refactoring code using newer Python features.

### PR DESCRIPTION
**Pull request by cooperlees**
- Update setup.cfg
  - Move to version 5.0.0.dev0
- Reomve uneeded '' dependency now we're >= 3.8
- Update GitHub Actions + TravisCI
- Add to CHANGES.md
- Update docs/CONTRIBUTION.md + rm duplicate DEVELOPMENT.md
- Remove outdated and no longer used bootstrap.sh

Fixes #788

### CODE REVIEW

**Comment by cooperlees** [comment]
@dralley + @gerrod3 - Does this make life hard for Pulp? Can it use the Docker image?

**Comment by cooperlees** [comment]
@techalchemy - Does >= 3.8 make life hard for cannonical peoples?

**Comment by dralley** [comment]
I would strongly prefer not to merge this, personally.   We would want to stick with 0.4 for a year or two, and just backport any important bugfixes, since we support Python 3.6+ and try to have RPM packages for direct installation on RHEL / CentOS.

We don't actually do that (RPM packages) for the Python plugin, currently, but it would prevent us from doing so.

**Comment by cooperlees** [comment]
I'm confused with that response. Just so it's known, I am not 100% all in on the move to 3.8, but I'd strongly like to. This PR is to discuss it. If there is good benefit to stay 3.6 - we will.

Are you happy to stick with 4.X for 3.6 + 3.7? Any important fixes we could make a branch and backport if needed just for pulp/redhat peoples ... depending how different the 3.8 refactored code is.

I also feel we live in a very different world now. It's super easy (and I just installed latest CentOS Stream to test) use `systemd-nspawn` to load a container image with a newer python (e.g. python 3.8). I even tested with an official Redhat Fedora image too.

The main reasons I'm interested in moving 5.0.0 to >= 3.8 are:
- I'd like to use the walrus operator in some places
- Refactor some of the asyncio using newer APIs
- Also I'd like to move off asynctest to mock.AsyncMock for typing + getting rid of warnings with old `@coroutine` decorators in asynctest etc. (there is also a third party backport we could use if 3.6 is still best for bandersnatch users)

I am sure we can find more reasons too. I feel with containers, we can move faster. Python runtime is pretty well tested. I also know some large companies who move fast with Python runtimes and are doing fine taking that low risk in the 2020's :).

This is all open for debate. I'm just a move forward kind of guy. I got strong opposition when I cut off Python 2 and <= 3.5 for bandersnatch years ago too, I expect the same here. I feel computing and "versioning" + "stable" has changed with our much strong TDD.

**Comment by cooperlees** [comment]
Another strong point is aiohttp moving to 3.7+ in 4.0:

```python
if sys.version_info < (3, 7):
    raise RuntimeError("aiohttp 4.x requires Python 3.7+")
```

^^ setup.py of master aiohhtp as of today.

**Comment by dralley** [comment]
It probably doesn't help that I totally mixed up the numbers and worded it poorly :P  Sorry about that, my bad.

What I meant was, yeah, as we can backport any important bugfixes to 0.4 and get a new release, we would have no problems with 0.5+ making whatever changes.

> I also feel we live in a very different world now. It's super easy (and I just installed latest CentOS Stream to test) use systemd-nspawn to load a container image with a newer python (e.g. python 3.8). I even tested with an official Redhat Fedora image too.

I get what you're saying, but there's a few reasons why it's not that simple.

Pulp isn't really a self-contained piece of software.  We don't just "support RPM & Python packages and Docker containers", we have a platform that supports plugins for Debian, RPM, docker, python, ruby, ansible, NPM, etc.  And not all of those plugins are maintained by "us" -- the Debian and Ruby plugins are actively developed by third parties, and we know of organizations that have written their own custom plugins in the past for internal use.

Which is awesome!  But the flip side is that while we do actually produce a container image with several of the most popular plugins, we still need to support users that want to install third-party ones, or produce their own plugins, or try out our own plugins that aren't yet at "production quality".

Another thing is that Pulp is itself used as a part of other projects.  Foreman is a web GUI for server lifecycle management, and it supports [many plugins](https://theforeman.org/plugins/)... and one of those plugins is Katello, which provides a web GUI for Pulp.  Earlier when I said that that "we" try to produce RPM packages, that's actually not true.  The Pulp project doesn't do that, but the Katello project does, because Katello uses Pulp.  And both Foreman and Katello are installed by Deb/RPM packages.

So while life would be sooooooooooooo much easier as a developer if we just produced a piece of software that does X, Y, and Z and productised it and called it a day, we're really quite serious about the whole community-building aspect of having a platform where people can write their own stuff without forking the entire project.  And there are legitimate upsides to that which make the downsides easier to swallow :)

**Comment by dralley** [comment]
I messed up the numbers again, geez.  I blame 2020.

**Comment by cooperlees** [comment]
No one yelled and we'll work with pulp support as needed in a 4.x branch when / if ever needed :) Going to merge.

**Pull request merged**
