### PR TITLE
Run yesqa against all the files

### PR DESCRIPTION
**Pull request by asottile**
https://github.com/asottile/yesqa

I had to [manually edit one comment][0].

- this line previously excluded any lint on that line
- `noqa` comments for a specific code [need a `:`][1] (yeah, their comment is
  wrong)
- yesqa knows this so it converted `# noqa F821` -> `# F821`

[0]: https://github.com/pypa/bandersnatch/blob/ccc9a38/src/bandersnatch/package.py#L89
[1]: https://github.com/PyCQA/flake8/blob/3.5.0/src/flake8/defaults.py#L49

### CODE REVIEW

**Comment by cooperlees** [comment]
So these are all things that pass now so we can remove?

**Comment by asottile** [comment]
yep!

**Comment by asottile** [comment]
`flake8` will read from a number of files by default, including `tox.ini` so that should (?) already work

**Comment by cooperlees** [comment]
Hmmm ok, will add if I see these errors come back.

**Pull request merged**
