### PR TITLE
bug fix: reading either default or system configuration instead of both

### PR DESCRIPTION
**Pull request by GreatBahram**
I fixed this [issue](https://github.com/pypa/bandersnatch/issues/95). #95 
I think the problem was configuration module tries to read default and system configuration. The problem is when you comment any section in system configuration, it'll read that section through default configuration.

### CODE REVIEW

**Comment by cooperlees** [comment]
Thanks for this!

Seems we need to always add an empty [blacklist] section - Please look at the failing tests and fix the code so we always atleast have an empty list. Or we will need to fix the plugin + tests to not require this.

You can run tests locally by installing and running `tox` from the root of the bandersnatch directory.

Looking deeply and my running 3.1.1 in prod, it seems this is just cosmetic and the code actually works. We could exempt these from printing the logs for example1 and example2
- calling on @dwighthubbard to suggest too please!

**Comment by GreatBahram** [comment]
Check it now, please. I made the changes you said

**Comment by cooperlees** [comment]
I did notice that, and I tried to clean it all up, but I got a lot of main test failures and didn't want to attack it. PRs welcome if all CI tests pass.

**Comment by GreatBahram** [comment]
OK, I'll work on it. should I open an issue for that?

**Comment by cooperlees** [comment]
I'm a less formal guy and this is general cleanup - Happy for no Issue.

**Comment by GreatBahram** [comment]
OK, @cooperlees. The problem is like the previous one, we should clear `Singleton._instances` for each test case. the problem is, these test case are some normal function I mean they're not class that inherited from `unittest.TestCase` and I have no idea how to write setUp function without class, maybe I should put all the test cases inside a class?
other ideas?

**Comment by GreatBahram** [comment]
I've just fixed that. I'll send the PR

**Pull request merged**
