### PR TITLE
Update / cleanup stuff relating to Python 3.7 and below

### PR DESCRIPTION
**Pull request by ichard26**
A PR fully created with the GitHub Web UI, aww yea!

### CODE REVIEW

**Comment by ichard26** [comment]
Dammit using the web UI was a bad idea. On the upside we get to say goodbye to a few type ignore comments :)

**Comment by ichard26** [comment]
Actually I found even more stuff related to Python 3.7 and below .... ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh. Give me a moment!

**Comment by ichard26** [comment]
Cool, that should be all of them, except for one of them since changing it probably affects how bandersnatch can be called:

https://github.com/pypa/bandersnatch/blob/c3673b9024bec0b201788ec9cfa28af81b840017/src/bandersnatch/main.py#L203-L209

`asyncio.run` doesn't support using an already running event loop if I can read docs properly.

**Comment by cooperlees** [comment]
> Cool, that should be all of them, except for one of them since changing it probably affects how bandersnatch can be called:
> 
> https://github.com/pypa/bandersnatch/blob/c3673b9024bec0b201788ec9cfa28af81b840017/src/bandersnatch/main.py#L203-L209
> 
> `asyncio.run` doesn't support using an already running event loop if I can read docs properly.

If people are calling bandersnatch I doubt they are using main.py. If they are we have some refactoring to do.

Thanks @ichard26! Sometimes I question keeping the coverage bot ... all open to suggestions there.

**Review by cooperlees — APPROVED** [review]

**Pull request merged**
