### PR TITLE
Add GH Action for pushing to Docker Hub on Release

### PR DESCRIPTION
**Pull request by SanketDG**
Added the Github Action for automating pushing the `pypa/bandersnatch`
image to Docker Hub when a new release in published.

Closes https://github.com/pypa/bandersnatch/issues/88

### CODE REVIEW

**Comment by SanketDG** [comment]
I see.

Would using We can always use https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#tag_names to tag the images work out?

**Comment by cooperlees** [comment]
Yup - Seems all we need is `tag_names: true` in .github/workflows/docker_upload.yml. Thanks for finding that!

**Comment by cooperlees** [comment]
There might be a race before the commit gets the release tag ...
- I wonder if it's re-ran when a tag is applied?

**Comment by SanketDG** [comment]
> I wonder if it's re-ran when a tag is applied?

Interesting, let me test this out.

**Comment by SanketDG** [comment]
This is blocked for the meantime, my local Docker instance seems to be causing issues.

**Comment by SanketDG** [comment]
Pulled this from the graves! Apologies, I get what I deserve for distrohopping so frequently!
I have updated the changes to use `tag_names` for releases.

> There might be a race before the commit gets the release tag ...
> 
> * I wonder if it's re-ran when a tag is applied?

So I tested this, and it seems like it only tags the image when an *annotated* tag (which is a tag + commit) is pushed, so it only creates an image with the tag name.

**Pull request merged**
