### PR TITLE
Add linux platform types based on PEP 599

### PR DESCRIPTION
**Pull request by rigelifland**
Will add platform tags specified in PEP 599 to `exclude_platform` filter:

- `manylinux2014_x86_64`
- `manylinux2014_i686`
- `manylinux2014_aarch64`
- `manylinux2014_armv7l`
- `manylinux2014_ppc64`
- `manylinux2014_ppc64le`
- `manylinux2014_s390x`

Addresses the PEP 599 portion of #830

### CODE REVIEW

**Review by cooperlees — APPROVED** [review]
Agree with this to unblock, but one day I might open an issue with packaging to add this list there so we have a source of truth.

**Comment by cooperlees** [comment]
@rigelifland - Can you just fix the black formatting please.
tox with lint should (or just directly runnig pre-commit) should repro the formatting. it's on `src/bandersnatch_filter_plugins/filename_name.py`

**Comment by rigelifland** [comment]
Should be fixed now.

**Comment by cooperlees** [comment]
LGTM. Thanks!

**Pull request merged**
