### PR TITLE
Revert setup.py to specify unversioned deps

### PR DESCRIPTION
**Pull request by cooperlees**
- Lets allow people to install latest deps
- Leave requirements.txt that hard pin known working versions
Test install in a venv: https://pastebin.com/FUzsgcX6

Addresses #81

### CODE REVIEW

**Comment by ewdurbin** [comment]
I'm -1 on this as it will leave `pip install bandersnatch` at the whimsy of our dependencies.

I realize that moving to pinned deps is a newer thing, but is arguably the correct choice for ensuring that `pip install bandersnatch` creates a working bandersnatch installation.

**Comment by ewdurbin** [comment]
Suggested alternatives:

  - Get [pyup](https://pyup.io) or [dependabot](https://dependabot.com) wired up on the repo to consistently be updating our `requirements.txt` to effectively "test" the behavior of fresh bandersnatch installations "in the field". Cut new releases as we fix compatibility.
  - Stick with pinned deps, upgrade them as often as possible. ([pyup](https://pyup.io) or [dependabot](https://dependabot.com)) could help here.
  - Build out a complex matrix of tests for varying versions of dependencies and get busy trying to maintain compatibility across them.

**Comment by cooperlees** [comment]
My goal was eventually to get pyup / something to auto update and keep requirements.txt doing exactly this.

The hard pinning works great for environments that use venvs per app, or blindly pull in deps from PyPI, but not everywhere (Facebook bias here) do that. This hard pinning causes issues if shared internal built + tested versions of said dependencies are not to the exact release version pinned to.

I feel offering both a requirements.txt with the pinned versions allows people to do either. That is:
```
# People who want pinned:
pip install -r requirements.txt bandersnatch
# People who want freedom + live with the risk
pip install bandersnatch
```

**Comment by yeraydiazdiaz** [comment]
Can I ask what's the main use case for bandersnatch?

To me it feels like it's an application that uses `pip` as its installation mechanism, which is a slightly awkward place to be since, as @cooperlees mentions, it almost forces the user to create a venv just for it or only install other packages that are fairly looser in their dependencies.

If that's the case I'd side with having pinned dependencies by default and having instructions as to how to install it with unpinned (or possibly `>=`) versions for the less common case the user needs to install alongside other packages.

**Comment by ewdurbin** [comment]
Little bit of a broader discussion, but when I consider tools like:

- `pip` and `virtualenv`
- [`awscli`](https://github.com/aws/aws-cli/blob/8d3117aa6349bbc1a765df61d9febc0b5fd8cd7f/setup.py#L26-L31)
- [`black`](https://github.com/ambv/black/blob/e4e59f87a8c4d3844dca9a14b6a4abf544c7a0c8/setup.py#L44)
- [`tox`](https://github.com/tox-dev/tox/blob/1e8fa7ba9d88aefb1888cc0a951a252f7098f311/setup.py#L29-L37)

That have a place as general purpose utilities they choose one of two routes:

- Vendor _everything_ (`pip`, `virtualenv`)
- Have lax but well specified ranges of dependencies (`awscli`, `black`, `tox`)

None of these are "applications" per say but utilities or command line tools. This is rather similar to bandersnatch after all... it's just a script that happens to create a mirror of PyPI then keep it up to date.

Is `pip install` the best way to distribute these? Maybe not. But they should be reliable.

I'm in favor of unpinned but ranged dependencies if we're testing within that range. It's the right middle ground between pinned and chaos.

**Comment by ewdurbin** [comment]
wrong button :-D

**Pull request merged**
