### PR TITLE
Fixes for https://github.com/pypa/bandersnatch/issues/196

### PR DESCRIPTION
**Pull request by rene-d**
Sorry one PR... read your message too late

* `verify.py` applies filters like Package to prevent downloading unwanted files
* latest releases filter always keeps the official version

### CODE REVIEW

**Comment by cooperlees** [comment]
Many thanks for this!

I'm sorry - But I've gone and done a pretty large PR (#197) that I think we should land and then re-apply this diff on. Thoughts?

Also, could verify just include the class from `src/bandersnatch/filter.py` and use that somehow rather than duplicating the logic? (I haven't looked to hard into it)

**Comment by rene-d** [comment]
Yes ok. I'll split the patch, and rebase my dev branch when your PR will be merged. 

And you're right, I have almost copy/paste some logic from Package.py to verify.py. I'm not very proud, but I didn't see how to do without refactoring filters and package.py.

**Comment by rene-d** [comment]
The main idea is to replace FilterReleasePlugin and FilterFilenamePlugin (the new one I introduced for my needs - that was an error...) to a new kind of plugin that takes the whole JSON data as parameter.

So, just two kinds of filters:
* FilterProjectPlugin -> applied on the list of packages (whitelist/blacklist)
* FilterMetadataPlugin -> applied on the metadata of a package, which can remove releases and/or dist files on various criteria.

**Comment by cooperlees** [comment]
Ok - I've merged my diff! Let me know if I can help. I could look at later this weekend using the `filter.py` logic in verify.

**Comment by cooperlees** [comment]
I’m looking to cut 3.3.1 over the weekend. Are you going to have time to polish this up (all good if not - this can go in 3.3.2)?

**Comment by rene-d** [comment]
I don't know yet, maybe tonight :)

**Comment by rene-d** [comment]
Hello @cooperlees, I prefer to take my time to propose more consistent changes. FilterReleasePlugin filters could take the whole metadata. Up to the plugin to remove or keep releases and/or filenames from this.

**Comment by cooperlees** [comment]
No problems! Take your time. Thanks for the PRs. I’ll cut 3.3.1 later today. I want to roll the nicer logging into my production tomorrow :)

**Comment by rene-d** [comment]
Hello @cooperlees 
I will submit another PR with those changes.
We can cancel this one.

**Pull request closed without merging**
